# Generated by Django 5.2.10 on 2026-01-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_ticket'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('movie_session', 'row', 'seat'), name='unique_movie_session'),
        ),
    ]
